# START WINDOW
START_WINDOW_WIDTH = 800
START_WINDOW_HEIGHT = 600


# SELECT WINDOW
SELECT_WINDOW_WIDTH = 682
SELECT_WINDOW_HEIGHT = 516


# PLAY WINDOW
PLAY_WINDOW_WIDTH = 950
PLAY_WINDOW_HEIGHT = 778


# PLAYER
SPACESHIP_VELOCITY = 10
SPACESHIP_WIDTH = 72
SPACESHIP_HEIGHT = 72

PLAYER_START_X = 15
PLAYER_START_Y = 655


# ALIEN
ALIEN_X_VELOCITY = 1
ALIEN_Y_VELOCITY = 5

FIRST_ROW_ALIEN_WIDTH = 72
FIRST_ROW_ALIEN_HEIGHT = 36

SECOND_ROW_ALIEN_WIDTH = 57
SECOND_ROW_ALIEN_HEIGHT = 39

THIRD_ROW_ALIEN_WIDTH = 54
THIRD_ROW_ALIEN_HEIGHT = 56

FOURTH_ROW_ALIEN_WIDTH = 57
FOURTH_ROW_ALIEN_HEIGHT = 57

FIFTH_ROW_ALIEN_WIDTH = 54
FIFTH_ROW_ALIEN_HEIGHT = 56

ALIEN_START_X = 50
ALIEN_START_Y = 86

ALIEN_OFFSET_X = 70
ALIEN_OFFSET_Y = 50
ALIEN_SECOND_ROW_OFFSET = 80


# ALIEN BULLET
ALIEN_BULLET_WIDTH = 45
ALIEN_BULLET_HEIGHT = 45
ALIEN_BULLET_VELOCITY = 4
ALIEN_SHOOT_INTERVAL = 3


# BULLET
BULLET_WIDTH = 45
BULLET_HEIGHT = 45
BULLET_VELOCITY = 10


# SHIELD
SHIELD_WIDTH = 85
SHIELD_HEIGHT = 105

SHIELD_START_X = 50
SHIELD_START_Y = 520

SHIELD_OFFSET_X = 260


MOVEMENT_SLEEP = 0.02


